[".config/zsh/oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    exact = true
    refreshPeriod = "672h"

[".config/zsh/custom/plugins/fast-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    exact = true
    refreshPeriod = "672h"

[".config/zsh/custom/plugins/zsh-autocomplete"]
    type = "git-repo"
    url = "https://github.com/marlonrichert/zsh-autocomplete.git"
    exact = true
    refreshPeriod = "672h"
