[".config/zsh/oh-my-zsh"]
    type = "git-repo"
    url = "https://github.com/ohmyzsh/ohmyzsh.git"
    exact = true
    refreshPeriod = "672h"

[".config/zsh/custom/plugins/fast-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/fast-syntax-highlighting.git"
    exact = true
    refreshPeriod = "672h"

[".config/zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions"
    exact = true
    refreshPeriod = "672h"

[".config/zsh/custom/plugins/zsh-completion"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-completions.git"
    exact = true
    refreshPeriod = "672h"

[".config/zsh/custom/plugins/fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab.git"
    exact = true
    refreshPeriod = "672h"
