#ZSH_HIGHLIGHT_STYLES[default]="none"
#ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=red,bold"
#ZSH_HIGHLIGHT_STYLES[reserved-word]="fg=magenta"
ZSH_HIGHLIGHT_STYLES[alias]="none"
ZSH_HIGHLIGHT_STYLES[builtin]="magenta,bold"
ZSH_HIGHLIGHT_STYLES[function]="none"
ZSH_HIGHLIGHT_STYLES[command]="none"
ZSH_HIGHLIGHT_STYLES[precommand]="none"
ZSH_HIGHLIGHT_STYLES[commandseparator]="none"
ZSH_HIGHLIGHT_STYLES[hashed-command]="none"
ZSH_HIGHLIGHT_STYLES[path]="fg=white,bold"
ZSH_HIGHLIGHT_STYLES[globbing]="fg=white,bold"
#ZSH_HIGHLIGHT_STYLES[history-expansion]="fg=blue"
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]="fg=cyan"
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]="fg=cyan,bold"
#ZSH_HIGHLIGHT_STYLES[back-quoted-argument]="none"
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]="fg=green"
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]="fg=green"
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]="fg=yellow"
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]="fg=yellow"
#ZSH_HIGHLIGHT_STYLES[assign]="none"

#ZSH_HIGHLIGHT_STYLES[bracket-level-1]="fg=cyan,bold"
#ZSH_HIGHLIGHT_STYLES[bracket-level-2]="fg=blue,bold"
#ZSH_HIGHLIGHT_STYLES[bracket-level-3]="fg=yellow,bold"
#ZSH_HIGHLIGHT_STYLES[bracket-level-4]="fg=magenta,bold"

